# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  apiproducer:
    image: apiproducer
    build:
      context: .
      dockerfile: src/api-producer/Dockerfile
    ports:
      - 5000
